// Package repository stores and retrieves weather data.
//
// Read queries are generated by sqlc (see gen/). The two bulk upserts are
// hand-written: they use multi-argument unnest to write a whole snapshot in one
// round trip, which sqlc's static analyzer cannot type without a live database
// at generation time.
package repository

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/desmondhiew00/jma-weather-api/internal/domain"
	"github.com/desmondhiew00/jma-weather-api/internal/repository/gen"
)

// ErrNotFound is returned when no row matches.
var ErrNotFound = errors.New("not found")

// Repository is the data access layer.
type Repository struct {
	pool *pgxpool.Pool
	q    *gen.Queries
}

// New wraps a pgx pool.
func New(pool *pgxpool.Pool) *Repository {
	return &Repository{pool: pool, q: gen.New(pool)}
}

// UpsertStations replaces the station master list.
//
// Retired stations keep their row rather than being deleted: observations
// reference them by foreign key, retention clears those within a week, and
// coordinate resolution only ever considers the freshly fetched list.
func (r *Repository) UpsertStations(ctx context.Context, stations []domain.Station) error {
	if len(stations) == 0 {
		return nil
	}

	n := len(stations)
	ids := make([]string, n)
	kanji := make([]string, n)
	kana := make([]string, n)
	en := make([]string, n)
	lats := make([]float64, n)
	lons := make([]float64, n)
	alts := make([]*int32, n)
	elems := make([]string, n)

	for i, s := range stations {
		ids[i], kanji[i], kana[i], en[i] = s.ID, s.NameKanji, s.NameKana, s.NameEn
		lats[i], lons[i], alts[i], elems[i] = s.Lat, s.Lon, s.AltitudeM, s.Elems
	}

	const q = `
INSERT INTO stations (id, name_kanji, name_kana, name_en, lat, lon, altitude_m, elems, updated_at)
SELECT *, now() FROM unnest($1::text[], $2::text[], $3::text[], $4::text[],
                            $5::double precision[], $6::double precision[],
                            $7::integer[], $8::text[])
ON CONFLICT (id) DO UPDATE SET
    name_kanji = EXCLUDED.name_kanji,
    name_kana  = EXCLUDED.name_kana,
    name_en    = EXCLUDED.name_en,
    lat        = EXCLUDED.lat,
    lon        = EXCLUDED.lon,
    altitude_m = EXCLUDED.altitude_m,
    elems      = EXCLUDED.elems,
    updated_at = now()`

	if _, err := r.pool.Exec(ctx, q, ids, kanji, kana, en, lats, lons, alts, elems); err != nil {
		return fmt.Errorf("upsert %d stations: %w", n, err)
	}

	return nil
}

// UpsertObservations writes a whole snapshot in one statement.
//
// DO UPDATE rather than DO NOTHING: a five-minute poll of ten-minute data
// re-reads the same record constantly, so the write must be idempotent, and
// upserting also picks up JMA's corrections to an already-stored reading.
func (r *Repository) UpsertObservations(ctx context.Context, obs []domain.Observation) error {
	if len(obs) == 0 {
		return nil
	}

	n := len(obs)
	ids := make([]string, n)
	at := make([]time.Time, n)
	cols := make([][]*float64, 13)

	for c := range cols {
		cols[c] = make([]*float64, n)
	}

	for i, o := range obs {
		ids[i], at[i] = o.StationID, o.ObservedAt

		for c, v := range [13]*float64{
			o.TempC, o.HumidityPct, o.PressureHpa, o.WindMs, o.WindDirectionDeg,
			o.Precipitation10mMm, o.Precipitation1hMm, o.Precipitation3hMm, o.Precipitation24hMm,
			o.Sun10mMin, o.Sun1hH, o.SnowCm, o.VisibilityM,
		} {
			cols[c][i] = v
		}
	}

	const q = `
INSERT INTO observations (
    station_id, observed_at,
    temp_c, humidity_pct, pressure_hpa, wind_ms, wind_direction_deg,
    precipitation_10m_mm, precipitation_1h_mm, precipitation_3h_mm, precipitation_24h_mm,
    sun_10m_min, sun_1h_h, snow_cm, visibility_m)
SELECT * FROM unnest($1::text[], $2::timestamptz[],
    $3::double precision[], $4::double precision[], $5::double precision[],
    $6::double precision[], $7::double precision[], $8::double precision[],
    $9::double precision[], $10::double precision[], $11::double precision[],
    $12::double precision[], $13::double precision[], $14::double precision[],
    $15::double precision[])
ON CONFLICT (station_id, observed_at) DO UPDATE SET
    temp_c               = EXCLUDED.temp_c,
    humidity_pct         = EXCLUDED.humidity_pct,
    pressure_hpa         = EXCLUDED.pressure_hpa,
    wind_ms              = EXCLUDED.wind_ms,
    wind_direction_deg   = EXCLUDED.wind_direction_deg,
    precipitation_10m_mm = EXCLUDED.precipitation_10m_mm,
    precipitation_1h_mm  = EXCLUDED.precipitation_1h_mm,
    precipitation_3h_mm  = EXCLUDED.precipitation_3h_mm,
    precipitation_24h_mm = EXCLUDED.precipitation_24h_mm,
    sun_10m_min          = EXCLUDED.sun_10m_min,
    sun_1h_h             = EXCLUDED.sun_1h_h,
    snow_cm              = EXCLUDED.snow_cm,
    visibility_m         = EXCLUDED.visibility_m`

	args := []any{ids, at}
	for _, c := range cols {
		args = append(args, c)
	}

	if _, err := r.pool.Exec(ctx, q, args...); err != nil {
		return fmt.Errorf("upsert %d observations: %w", n, err)
	}

	return nil
}

// ListStations returns every known station.
func (r *Repository) ListStations(ctx context.Context) ([]domain.Station, error) {
	rows, err := r.q.ListStations(ctx)
	if err != nil {
		return nil, fmt.Errorf("list stations: %w", err)
	}

	stations := make([]domain.Station, 0, len(rows))
	for _, s := range rows {
		stations = append(stations, domain.Station{
			ID:        s.ID,
			NameKanji: s.NameKanji,
			NameKana:  deref(s.NameKana),
			NameEn:    deref(s.NameEn),
			Lat:       s.Lat,
			Lon:       s.Lon,
			AltitudeM: s.AltitudeM,
			Elems:     deref(s.Elems),
		})
	}

	return stations, nil
}

// CountStations reports how many stations are stored. A cold start with zero is
// the one case where a failed station fetch is fatal.
func (r *Repository) CountStations(ctx context.Context) (int64, error) {
	n, err := r.q.CountStations(ctx)
	if err != nil {
		return 0, fmt.Errorf("count stations: %w", err)
	}

	return n, nil
}

// LatestObservedAt is the ingest watermark: the newest observation stored.
// Zero time means the table is empty.
func (r *Repository) LatestObservedAt(ctx context.Context) (time.Time, error) {
	ts, err := r.q.LatestObservedAt(ctx)
	if err != nil {
		return time.Time{}, fmt.Errorf("latest observed_at: %w", err)
	}

	if !ts.Valid {
		return time.Time{}, nil
	}

	return ts.Time.UTC(), nil
}

// LatestForStation returns a station's newest observation.
func (r *Repository) LatestForStation(ctx context.Context, stationID string) (domain.Observation, error) {
	row, err := r.q.LatestForStation(ctx, stationID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return domain.Observation{}, ErrNotFound
		}

		return domain.Observation{}, fmt.Errorf("latest for %s: %w", stationID, err)
	}

	return toDomain(row), nil
}

// LatestForAllStations returns each station's newest reading, ignoring stations
// whose last reading is older than earliest. A station that went silent is
// therefore absent rather than present with a stale value.
func (r *Repository) LatestForAllStations(ctx context.Context, earliest time.Time) ([]domain.Observation, error) {
	rows, err := r.q.LatestForAllStations(ctx, ts(earliest))
	if err != nil {
		return nil, fmt.Errorf("latest for all stations: %w", err)
	}

	obs := make([]domain.Observation, 0, len(rows))
	for _, row := range rows {
		obs = append(obs, toDomain(row))
	}

	return obs, nil
}

// HistoryForStation returns observations in [from, to].
func (r *Repository) HistoryForStation(ctx context.Context, stationID string, from, to time.Time) ([]domain.Observation, error) {
	rows, err := r.q.HistoryForStation(ctx, gen.HistoryForStationParams{
		StationID: stationID,
		FromTime:  ts(from),
		ToTime:    ts(to),
	})
	if err != nil {
		return nil, fmt.Errorf("history for %s: %w", stationID, err)
	}

	obs := make([]domain.Observation, 0, len(rows))
	for _, row := range rows {
		obs = append(obs, toDomain(row))
	}

	return obs, nil
}

// ObservationAt returns the reading current at bucket, looking no further back
// than earliest. A station outage therefore yields ErrNotFound rather than a
// silently stale answer.
func (r *Repository) ObservationAt(ctx context.Context, stationID string, bucket, earliest time.Time) (domain.Observation, error) {
	row, err := r.q.ObservationAt(ctx, gen.ObservationAtParams{
		StationID: stationID,
		Bucket:    ts(bucket),
		Earliest:  ts(earliest),
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return domain.Observation{}, ErrNotFound
		}

		return domain.Observation{}, fmt.Errorf("observation at for %s: %w", stationID, err)
	}

	return toDomain(row), nil
}

// DeleteOlderThan enforces retention and reports how many rows went.
func (r *Repository) DeleteOlderThan(ctx context.Context, cutoff time.Time) (int64, error) {
	n, err := r.q.DeleteOlderThan(ctx, ts(cutoff))
	if err != nil {
		return 0, fmt.Errorf("delete before %s: %w", cutoff, err)
	}

	return n, nil
}

func toDomain(o gen.Observation) domain.Observation {
	return domain.Observation{
		StationID:          o.StationID,
		ObservedAt:         o.ObservedAt.Time.UTC(),
		TempC:              o.TempC,
		HumidityPct:        o.HumidityPct,
		PressureHpa:        o.PressureHpa,
		WindMs:             o.WindMs,
		WindDirectionDeg:   o.WindDirectionDeg,
		Precipitation10mMm: o.Precipitation10mMm,
		Precipitation1hMm:  o.Precipitation1hMm,
		Precipitation3hMm:  o.Precipitation3hMm,
		Precipitation24hMm: o.Precipitation24hMm,
		Sun10mMin:          o.Sun10mMin,
		Sun1hH:             o.Sun1hH,
		SnowCm:             o.SnowCm,
		VisibilityM:        o.VisibilityM,
	}
}

func ts(t time.Time) pgtype.Timestamptz {
	return pgtype.Timestamptz{Time: t, Valid: true}
}

func deref(s *string) string {
	if s == nil {
		return ""
	}

	return *s
}
